STATE_CHOICES = (
    ('bogota', 'Bogotá D.C'),
    ('amazonas', 'Amazonas'),
    ('antioquia', 'Antioquía'),
    ('arauca', 'Arauca'),
    ('atlantico', 'Atlántico'),
    ('bolivar', 'Bolívar'),
    ('boyaca', 'Boyacá'),
    ('caldas', 'Caldas'),
    ('caquetá', 'Caquetá'),
    ('casanare', 'Casanare'),
    ('cauca', 'Cauca'),
    ('cesar', 'Cesar'),
    ('choco', 'Chocó'),
    ('cordoba', 'Córdoba'),
    ('cundinamarca', 'Cundinamarca'),
    ('guainia', 'Guainía'),
    ('guaviare', 'Guaviare'),
    ('huila', 'Huila'),
    ('guajira', 'Guajira'),
    ('magdalena', 'Magdalena'),
    ('meta', 'Meta'),
    ('nariño', 'Nariño'),
    ('norte_de_santander', 'Norte de Santander'),
    ('putumayo', 'Putumayo'),
    ('quindio', 'Quindío'),
    ('risaralda', 'Risaralda'),
    ('santander', 'Santander'),
    ('sucre', 'Sucre'),
    ('tolima', 'Tolima'),
    ('valle_del_cauca', 'Valle del Cauca'),
    ('vaupes', 'Vaupés'),
    ('vichada', 'Vichada'),
)