# Generated by Django 3.1.7 on 2021-04-11 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document_id', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('number_phone', models.CharField(max_length=10)),
                ('alternative_number_phone', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('bogota', 'Bogotá D.C'), ('amazonas', 'Amazonas'), ('antioquia', 'Antioquía'), ('arauca', 'Arauca'), ('atlantico', 'Atlántico'), ('bolivar', 'Bolívar'), ('boyaca', 'Boyacá'), ('caldas', 'Caldas'), ('caquetá', 'Caquetá'), ('casanare', 'Casanare'), ('cauca', 'Cauca'), ('cesar', 'Cesar'), ('choco', 'Chocó'), ('cordoba', 'Córdoba'), ('cundinamarca', 'Cundinamarca'), ('guainia', 'Guainía'), ('guaviare', 'Guaviare'), ('huila', 'Huila'), ('guajira', 'Guajira'), ('magdalena', 'Magdalena'), ('meta', 'Meta'), ('nariño', 'Nariño'), ('norte_de_santander', 'Norte de Santander'), ('putumayo', 'Putumayo'), ('quindio', 'Quindío'), ('risaralda', 'Risaralda'), ('santander', 'Santander'), ('sucre', 'Sucre'), ('tolima', 'Tolima'), ('valle_del_cauca', 'Valle del Cauca'), ('vaupes', 'Vaupés'), ('vichada', 'Vichada')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
        ),
    ]
