# Generated by Django 3.1.7 on 2021-05-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210522_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Esperando al pago'), ('payment_rejected', 'Pago rechazado'), ('failed_payment', 'Pago fallido'), ('preparing_shipment', 'Preparando para enviar'), ('on_the_way', 'En camino'), ('no_delivery_confirmation', 'Sin confirmación de llegada'), ('delivery_refused', 'Devuelto'), ('delivered', 'Entregado')], max_length=50),
        ),
    ]
