# Generated by Django 3.1.7 on 2021-03-23 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('video', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, help_text='Hexadecimal colors only', max_length=7, null=True)),
                ('height', models.FloatField(blank=True, help_text='Please add measurement in centimeters.', null=True)),
                ('width', models.FloatField(blank=True, help_text='Please add measurement in centimeters.', null=True)),
                ('length', models.FloatField(blank=True, help_text='Please add measurement in centimeters.', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Please add measurement in centimeters.', null=True)),
                ('material', models.CharField(blank=True, max_length=30, null=True)),
                ('size', models.FloatField(blank=True, choices=[('XS', 'XS: Extra Small'), ('S', 'S: Small'), ('M', 'M: Medium'), ('L', 'L: Large'), ('XL', 'XL: Extra Large'), ('XXL', 'XXL: Extra Extra Large')], null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='products/')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariation')),
            ],
        ),
    ]
