# Generated by Django 3.1.7 on 2021-03-26 18:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210325_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, null=True, size=None),
        ),
    ]
